name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
        env:
          JEKYLL_ENV: production

      - name: Copy htaccess file to _site
        run: mv .htaccess /_site/.htaccess

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@master
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PWD }}
          LOCAL_DIR: _site
          REMOTE_DIR: moraleda.info
          ARGS: --delete --transfer-all
          # --delete arg will delete files on the server if you've deleted them in git
